Upgrading PyYAML==5.4
prebid/line-item-manager pull request #137
Opened 2023-09-21 16:57 UTC by shuaibjewon-qz

2023-09-28 21:13 UTC, dshore commented
I don't think 5.4.1 will work, see:

2023-09-28 21:15 UTC, dshore commented
There is an issue with 5.4.1 which is why I downgraded:
[Error installing Pyyaml==5.4, Cython_sources](https://github.com/yaml/pyyaml/issues/724)

I would suggest we go to PyYAML==6.0.1 which requires upgrading googleads

2023-09-28 21:47 UTC, dshore commented on setup.py
>      'googleads==33.0.0',
```suggestion
    'googleads==39.0.0',
```

2023-09-28 21:48 UTC, dshore commented on setup.py
> +    'PyYAML==5.4',
```suggestion
    'PyYAML==6.0.1',
```

2023-09-28 21:49 UTC, dshore requested changes
PyYAML 5.4.1 has build issues

2023-09-28 23:42 UTC, dshore commented
Also, update this line to denote a dev release:
https://github.com/prebid/line-item-manager/blob/master/line_item_manager/__init__.py#L8

2023-09-29 13:22 UTC, dshore commented
I commit this in latest dev work

2023-09-29 13:22 UTC, closed without merging

2023-09-29 15:12 UTC, shuaibjewon-qz commented
Thanks for handling!