add sponsorship line item creation
prebid/line-item-manager pull request #87
Opened 2022-01-20 00:05 UTC by milesmahon

Add [support for sponsorship line items](https://github.com/prebid/line-item-manager/issues/86).

2022-01-25 13:47 UTC, dshore requested changes
If you bump this to '1' we can cut a dev release:
https://github.com/prebid/line-item-manager/blob/master/line_item_manager/__init__.py#L8
I like to use it for a few days at least before doing a tagged release, and publish to pypi.

2022-01-25 13:47 UTC, dshore commented on tests/resources/cfg.yml
> +# Supported Types: price_priority, standard, sponsorship
This should be added here as well:
https://github.com/prebid/line-item-manager/blob/master/line_item_manager/conf.d/line_item_manager.yml#L93

2022-01-25 13:47 UTC, dshore commented on tests/resources/cfg.yml
> +    # goalType: "LIFETIME"
This should be added here as well:
https://github.com/prebid/line-item-manager/blob/master/line_item_manager/conf.d/line_item_manager.yml#L103

2022-01-25 21:11 UTC, milesmahon commented
done with 3a9ca6c

2022-01-26 01:44 UTC, dshore approved these changes

2022-01-26 01:48 UTC, merged

2022-01-26 02:10 UTC, dshore commented
@milesmahon this is available as a dev release:
```
$ pip uninstall line-item-manager
$ pip install https://github.com/prebid/line-item-manager/archive/master.zip
$ line_item_manager --version
line-item-manager version 0.2.4-dev1
```